// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  APIUrl: 'http://localhost:51368/api/',
 // arcgisServerUrl: 'https://localhost:44379/arcgis/rest/services/',
  arcgisServerUrl: 'http://10.10.0.147/arcgis/rest/services/',
  GetAllEquipments: 'http://localhost:51368/api/Equipments/',
  GetAllMasterEquipmentWithPaging: 'http://localhost:51368/api/MasterEquipment/GetMasterEquipmentsWithPaging/',
  GetAllEquipmentWithPaging: 'http://localhost:51368/api/Equipments/GetEquipmentsWithPaging/',
  getEquipmentcount:'http://localhost:51368/api/MasterEquipment/getcount/',
  GetAllEquipmentsforinventory: 'http://localhost:51368/api/Equipments/inventories/', 
  GetAllEquipmentswithscanningDate:'http://localhost:51368/api/Equipments/scanningDate/',
  //upload:'http://localhost:51368/api/EquipmentAttachments/upload/',
  GetOneEquipment: 'http://localhost:51368/api/Equipments/',
  GetAllscannedequipments:'http://localhost:51368/api/Equipments/group',
  GetEquipmentAttachmentIDs:'http://localhost:51368/api/EquipmentAttachments/upload/',
  GetEquipmentAttachments:'http://localhost:51368/api/EquipmentAttachments/getEquipAttachmentsWithNoEquipment',
  AddNewEquipments: 'http://localhost:51368/api/Equipments/',
  DeleteEquipment: 'http://localhost:51368/api/Equipments/',
  UpdateEquipment: 'http://localhost:51368/api/Equipments/',
  GetAllHealthCareUnits: 'http://localhost:51368/api/HealthCareUnits/',
  DeleteHealthCareUnit: 'http://localhost:51368/api/HealthCareUnits/',
  updateHealthCareUnit: 'http://localhost:51368/api/HealthCareUnits/',
  GetAllHealthCareUnitsByDistrictId: 'http://localhost:51368/api/HealthCareUnits/GetHealthCareUnitsByDistrictId/',
  GetHospitalsCount:'http://localhost:51368/api/HealthCareUnits/getcount/',
  GetAllHospitalsWithPaging:'http://localhost:51368/api/HealthCareUnits/GetHospitalsWithPaging',
  // GetByDistrictId: 'http://localhost:51368/api/employees/getHealthDistrictsByempDistrictId/',
  GetByDirectoryId:'http://localhost:51368/api/HealthDistricts/getHealthDirectoryBydirId/',
  addNewUnit: 'http://localhost:51368/api/HealthCareUnits/',
  GetAllStatuses: 'http://localhost:51368/api/EquipmentStatus/',
  GetAllPriorities: 'http://localhost:51368/api/Priorities/',
  GetAllManufacturers: 'http://localhost:51368/api/Manufacturers/',
  GetAllOrigins: 'http://localhost:51368/api/Origins/',
  GetAllCategories: 'http://localhost:51368/api/EquipmentCategories/',
  GetSubCategories: 'http://localhost:51368/api/EquipmentSubCategories/',
  GetAllSubCategories: 'http://localhost:51368/api/EquipmentSubCategories/AllSubCategoriesBycategoryId/',
  GetAllDepartments: 'http://localhost:51368/api/Departments/',
  GetAllSuppliers: 'http://localhost:51368/api/Suppliers/',
  // GetAllEmployees: 'http://localhost:51368/api/employees/',
  // AddEmployee: 'http://localhost:51368/api/employees/',
  // DeleteEmployee: 'http://localhost:51368/api/employees/',
  // UpdateEmployee: 'http://localhost:51368/api/employees/',
  GetEquipment: 'http://localhost:51368/api/Equipments/',
  UploadImg: 'http://localhost:51368/api/ImgUpload/',
  GetAllServiceRequests: 'http://localhost:51368/api/ServiceRequests/',
  //  GetAllServiceRequestsByEmpEmail:'http://localhost:51368/api/ServiceRequests/GetAllRequestsByEmpEmail/',
  GetAllRequestsByDirectory: 'http://localhost:51368/api/ServiceRequests/GetAllRequestsByDirectory/',
  MakeRequest: 'http://localhost:51368/api/ServiceRequests',
  UpdateRequest: 'http://localhost:51368/api/ServiceRequests/',
  DeleteRequest: 'http://localhost:51368/api/ServiceRequests/',
  Register: 'http://localhost:51368/api/authenticate/register/',
  Login: 'http://localhost:51368/api/authenticate/login/',
  GetUsers: 'http://localhost:51368/api/User/',
  getUserscount:'http://localhost:51368/api/User/getcount/',
  getAllUserswithpaging:'http://localhost:51368/api/User/GetUsersWithPaging/',
  getUserById: 'http://localhost:51368/api/User/GetUserById/',
  DeleteUser: 'http://localhost:51368/api/User/',
  UpdateUser: 'http://localhost:51368/api/User/',
  GetUnregisteredUsers: 'http://localhost:51368/api/User/GetUnregisteredUsers/',
  GetAllRoles: 'http://localhost:51368/api/User/GetAllRoles/',
  getRoleById: 'http://localhost:51368/api/User/GetRoleById/',
  getEmployeeByMail: 'http://localhost:51368/api/Employees/GetEmployeeNyMail/',
  UpdateRole: 'http://localhost:51368/api/authenticate/ChangeRole/',
  GetAllHealthDirectories: 'http://localhost:51368/api/HealthDirectories/',
  // GetAllHealthDitricts:'http://localhost:51368/api/HealthDistricts/',
  GetAllHealthDitricts: 'http://localhost:51368/api/HealthDistricts/AllHealthDistrictsByhealthDirectoryId/',
  GetAllHealthDitrictsByDirectoryName: 'http://localhost:51368/api/HealthDistricts/AllHealthDistrictsByhealthDirectoryName/',
  //GetHealthDistrictIdByName:'http://localhost:51368/api/HealthDirectories/GetHealthDirectoryIdByName/',
  GetHealthDirectoryIdByName:'http://localhost:51368/api/HealthDirectories/GetHealthDirectoryIdByName/',
  GetHealthDistrictsIdbyName:'http://localhost:51368/api/HealthDistricts/GetHealthDistrictsIdbyName/',
  GetHealthDitricts: 'http://localhost:51368/api/HealthDistricts/',
  GetAllHealthCareUnitById:'http://localhost:51368/api/HealthCareUnits/',
  GetAllModes: 'http://localhost:51368/api/Mode/',
  GetAllEquimentsByEmp: 'http://localhost:51368/api/Equipments/GetAllEquimentsByEmp/',
  AddNewCategory: 'http://localhost:51368/api/EquipmentCategories/',
  updateCategory: 'http://localhost:51368/api/EquipmentCategories/',
  deleteCategory: 'http://localhost:51368/api/EquipmentCategories/',
  AddNewSubCategory: 'http://localhost:51368/api/EquipmentSubCategories/',
  updateSubCategory: 'http://localhost:51368/api/EquipmentSubCategories/',
  deleteSubCategory: 'http://localhost:51368/api/EquipmentSubCategories/',
  addNewOrigin: 'http://localhost:51368/api/Origins/',
  updateOrigin: 'http://localhost:51368/api/Origins/',
  deleteOrigin: 'http://localhost:51368/api/Origins/',
  addNewManufacturer: 'http://localhost:51368/api/Manufacturers/',
  updateManufacturer: 'http://localhost:51368/api/Manufacturers/',
  deleteManufacturer: 'http://localhost:51368/api/Manufacturers/',
  addNewStatus: 'http://localhost:51368/api/EquipmentStatus/',
  updateStatus: 'http://localhost:51368/api/EquipmentStatus/',
  deleteStatus: 'http://localhost:51368/api/EquipmentStatus/',
  addNewPriority: 'http://localhost:51368/api/Priorities/',
  updatePriority: 'http://localhost:51368/api/Priorities/',
  deletePriority: 'http://localhost:51368/api/Priorities/',
  addNewDepartment: 'http://localhost:51368/api/Departments/',
  updateDepartment: 'http://localhost:51368/api/Departments/',
  deleteDepartment: 'http://localhost:51368/api/Departments/',
  addNewSupplier: 'http://localhost:51368/api/Suppliers/',
  updateSupplier: 'http://localhost:51368/api/Suppliers/',
  deleteSupplier: 'http://localhost:51368/api/Suppliers/',
  addNewMode: 'http://localhost:51368/api/Mode/',
  updateMode: 'http://localhost:51368/api/Mode/',
  deleteMode: 'http://localhost:51368/api/Mode/',
  // GetEmployee: 'http://localhost:51368/api/employees/',
  GetEquipmentEmployee: 'http://localhost:51368/api/User/GetEquipmentemployees/',
  CreateRoles: 'http://localhost:51368/api/User/CreateRoles/',
  AddNewMasterEquipments: 'http://localhost:51368/api/MasterEquipment/',
  GetAllMasterEquipment: 'http://localhost:51368/api/MasterEquipment/',
  //GetAllMasterEquipmentWithPaging:'http://localhost:51368/api/MasterEquipment/GetMasterEquipmentsWithPaging/',
  UpdateMasterEquipment: 'http://localhost:51368/api/MasterEquipment/',
  DeleteMasterEquipment: 'http://localhost:51368/api/MasterEquipment/',
  GetVendors: 'http://localhost:51368/api/Vendor',
  AddNewWorkOrder: 'http://localhost:51368/api/WorkOrder',
  AddNewMaintenance: 'http://localhost:51368/api/Maintenance',
  AddNewSparePart: 'http://localhost:51368/api/SparePart',
  GetAllRequestStatus: 'http://localhost:51368/api/WorkOrder/GetAllRequestStatus',
  deleteWorkOrder: 'http://localhost:51368/api/WorkOrder/',
  createNewStatus: 'http://localhost:51368/api/ServiceRequests/createRequestStatus',
  getAllOworkOrders: 'http://localhost:51368/api/WorkOrder/',
  GetMaintenance: 'http://localhost:51368/api/Maintenance/',
  getOneWorkOrder: 'http://localhost:51368/api/WorkOrder/',
  GetSparePart: 'http://localhost:51368/api/SparePart/',
  UpdateWorkOrder: 'http://localhost:51368/api/WorkOrder/',
  UpdateMaintenance: 'http://localhost:51368/api/Maintenance/',
  DeleteWorkOrder: 'http://localhost:51368/api/WorkOrder/',
  AddWorkOrderWithoutRequest: 'http://localhost:51368/api/WorkOrder/AddWorkOrderWithoutRequest',
  getOrdersWithoutRequest: 'http://localhost:51368/api/WorkOrder/GetAllOrdersWithoutRequest',
  Closeorder: 'http://localhost:51368/api/WorkOrder/CloseWorkOrder/',
  forgetPassword: 'http://localhost:51368/api/Authenticate/forgetPassword/',
  resetpassword: 'http://localhost:51368/api/Authenticate/ResetPassword/',
  GetAllContracts: 'http://localhost:51368/api/contract/',
  AddContract: 'http://localhost:51368/api/contract/',
  DeleteContract: 'http://localhost:51368/api/contract/',
  UpdateContract: 'http://localhost:51368/api/contract/',
  GetAllEquipmentCoverages: 'http://localhost:51368/api/EquipmentCoverage/',
  AddEquipmentCoverage: 'http://localhost:51368/api/EquipmentCoverage/',
  DeleteEquipmentCoverage: 'http://localhost:51368/api/EquipmentCoverage/',
  UpdateEquipmentCoverage: 'http://localhost:51368/api/EquipmentCoverage/',
  GetAllSpareParts: 'http://localhost:51368/api/SparePart/',
  AddSparePart: 'http://localhost:51368/api/SparePart/',
  DeleteSparePart: 'http://localhost:51368/api/SparePart/',
  UpdateSparePart: 'http://localhost:51368/api/SparePart/',
  GetAllecriCodes:'http://localhost:51368/api/ecri/',
  updateEcriCode:'http://localhost:51368/api/ecri/',
  deleteEcriCode:'http://localhost:51368/api/ecri/',
  addEcriCode:'http://localhost:51368/api/ecri/',
  addNewecri:'http://localhost:51368/api/ecri/',
  //*************************************************************/
  GetAllOrganization:'http://localhost:51368/api/Organization/',
  GetAllOrganizationWithPaging:'http://localhost:51368/api/Organization/GetOrganizationsWithPaging/',
  getOrganizationscount:'http://localhost:51368/api/Organization/getcount',
  AddOrganization:'http://localhost:51368/api/Organization/',
  DeleteOrganization:'http://localhost:51368/api/Organization/',
  UpdateOrganization:'http://localhost:51368/api/Organization/', 
  GetOrganization:'http://localhost:51368/api/Organization/',
  GetAllUsersByHealthcareunitId:'http://localhost:51368/api/AllUsersByHealthcareunitId/',
  GetAllUsersByhealthDirectoryId:'http://localhost:51368/api/AllUsersByhealthDirectoryId/',
  GetAllUsersByhealthDistrictId:'http://localhost:51368/api/AllUsersByhealthDistrictId/',
  GetAllUsersByOrganizationId:'http://localhost:51368/api/AllUsersByOrganizationId/',
  GetALLSubOrganization:'http://localhost:51368/api/subOrganization/',
  AddNewSubOrganization: 'http://localhost:51368/api/subOrganization/',
  updateSubOrganization: 'http://localhost:51368/api/subOrganization/',
  deleteSubOrganization: 'http://localhost:51368/api/subOrganization/',
  GetSubOrganization:'http://localhost:51368/api/subOrganization/',
  getSubOrgscount:'http://localhost:51368/api/subOrganization/getcount',
  GetAllSubOrgsWithPaging:'http://localhost:51368/api/subOrganization/GetSubOrgsWithPaging/',

  GetAttachmentsForEquipment:'http://localhost:51368/api/EquipmentAttachments/getEquipAttachmentsForEquipment/',
  GetImagePath:'http://localhost:51368/api/EquipmentAttachments/getPathOfImage/',
  DeleteAttach:'http://localhost:51368/api/EquipmentAttachments/',
  GetAttachmentsForMasterEquipment:'http://localhost:51368/api/MasterEquipmentAttachment/getAttachmentsWithNoMasterEquipment/',
  GetMasterEquipmentAttachmentIDs:'http://localhost:51368/api/MasterEquipmentAttachment/Masterupload/',
  GetUsersByEquipmentId:'http://localhost:51368/api/user/GetEquipmentemployees/',
  GetAttachmentsForMEquipment:'http://localhost:51368/api/MasterEquipmentAttachment/getAttachmentsForMasterEquipment/',
  DeleteMasterAttach:'http://localhost:51368/api/MasterEquipmentAttachment/',
  getMasterByBrand:"http://localhost:51368/api/MasterEquipment/GetMasterByBrands/",
  GetEquipmentBymaster:"http://localhost:51368/api/Equipments/GetmasterEquipment/",
  GetAllByHospital:'http://localhost:51368/api/Equipments/GetEquipmentByHospital/',
  AddInInventory:'http://localhost:51368/api/Inventory/',
  getAllInventories:'http://localhost:51368/api/Inventory/',
  CreateQr: 'http://localhost:51368/api/QRCoder/Index/',
  GetEquipmentsOnGovernorate:'http://localhost:51368/api/Equipments/GetEquipByGovernorate/',
  GetEquipmentsOnCity:'http://localhost:51368/api/Equipments/GetEquipByDistrict/',
  GetEquipmentsOnOrganization:'http://localhost:51368/api/Equipments/GetEquipByOrganization/',
  GetEquipmentsOnSupplier:'http://localhost:51368/api/Equipments/GetEquipBySupplier/',
  FilterData:'http://localhost:51368/api/Equipments/FilterEquipment/',
  addEquipmentRecall:'http://localhost:51368/api/EquipmentRecall',
  GetAllRecalledEquipments:'http://localhost:51368/api/Equipments/recalledEqs',
  getEquipmentInHospital:'http://localhost:51368/api/Equipments/GetEquipmentInHospital/',
  AddContractRequest:'http://localhost:51368/api/ContractRequest/',
  AddOrganizationContractRequest:'http://localhost:51368/api/ContractRequest/AddOrganizationRequest/',
  getHosForOrganization:'http://localhost:51368/api/ContractRequest/GethospitalsInOrganization/',
  getRequestbetweenDates:'http://localhost:51368/api/ContractRequest/getRequestBetweenDates/',
  getRequestForUPA:'http://localhost:51368/api/ContractRequest/getRequestForUPA/',
  getEquipmentInContract:'http://localhost:51368/api/Equipments/getEquipmentInContract/',
  getOneContract:'http://localhost:51368/api/Contract/',
  EquipmentInContract:'http://localhost:51368/api/Equipments/EquipmentInContract/',
  getEquipmentsInContract:'http://localhost:51368/api/Equipments/getEquipmentsInContract/',
  getcount:'http://localhost:51368/api/MasterEquipment/getcount/',

  getRequestInHospitals:'http://localhost:51368/api/ContractRequest/GetRequestInHospital/',
  getCountOfRequestInHospital:'http://localhost:51368/api/ContractRequest/getcount/',
  updateRequestStatus:'http://localhost:51368/api/ContractRequest/UpdateRequestStatus/',
  getRequest:'http://localhost:51368/api/ContractRequest/getRequest/',
  updateContractRequest:'http://localhost:51368/api/ContractRequest/PutContractRequest/',
  getEquipmentInHospitalToEdit:'http://localhost:51368/api/Equipments/getEquipmentInHospitalToEdit/',
  delete:'http://localhost:51368/api/ContractRequest/Delete/',
  // Drug: 'http://localhost:51563/api/drugs/',
  // **************************************************************************
    // GetAllEquipments: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
  // GetOneEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
  // AddNewEquipments: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
  // DeleteEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
  // UpdateEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
  // GetAllHealthCareUnits: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/',
  // DeleteHealthCareUnit: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/',
  // updateHealthCareUnit: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/',
  // GetAllHealthCareUnitsByDistrictId: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/GetHealthCareUnitsByDistrictId/',
  // GetByDistrictId: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/getHealthDistrictsByempDistrictId/',
  // GetByDirectoryId:'http://almostakbalupd-001-site1.etempurl.com/api/HealthDistricts/getHealthDirectoryBydirId/',
  // addNewUnit: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/',
  // GetAllStatuses: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentStatus/',
  // GetAllPriorities: 'http://almostakbalupd-001-site1.etempurl.com/api/Priorities/',
  // GetAllManufacturers: 'http://almostakbalupd-001-site1.etempurl.com/api/Manufacturers/',
  // GetAllOrigins: 'http://almostakbalupd-001-site1.etempurl.com/api/Origins/',
  // GetAllCategories: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCategories/',
  // GetSubCategories: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentSubCategories/',
  // GetAllSubCategories: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentSubCategories/AllSubCategoriesBycategoryId/',
  // GetAllDepartments: 'http://almostakbalupd-001-site1.etempurl.com/api/Departments/',
  // GetAllSuppliers: 'http://almostakbalupd-001-site1.etempurl.com/api/Suppliers/',
  // GetAllEmployees: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/',
  // AddEmployee: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/',
  // DeleteEmployee: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/',
  // UpdateEmployee: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/',
  // GetEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
  // UploadImg: 'http://almostakbalupd-001-site1.etempurl.com/api/ImgUpload/',
  // GetAllServiceRequests: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests/',
  // GetAllRequestsByDirectory: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests/GetAllRequestsByDirectory/',
  // MakeRequest: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests',
  // UpdateRequest: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests/',
  // DeleteRequest: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests/',
  // Register: 'http://almostakbalupd-001-site1.etempurl.com/api/authenticate/register/',
  // Login: 'http://almostakbalupd-001-site1.etempurl.com/api/authenticate/Login',
  // GetUsers: 'http://almostakbalupd-001-site1.etempurl.com/api/User/',
  // getUserById: 'http://almostakbalupd-001-site1.etempurl.com/api/User/GetUserById/',
  // DeleteUser: 'http://almostakbalupd-001-site1.etempurl.com/api/User/',
  // GetUnregisteredUsers: 'http://almostakbalupd-001-site1.etempurl.com/api/User/GetUnregisteredUsers/',
  // GetAllRoles: 'http://almostakbalupd-001-site1.etempurl.com/api/User/GetAllRoles/',
  // getRoleById: 'http://almostakbalupd-001-site1.etempurl.com/api/User/GetRoleById/',
  // getEmployeeByMail: 'http://almostakbalupd-001-site1.etempurl.com/api/Employees/GetEmployeeNyMail/',
  // UpdateRole: 'http://almostakbalupd-001-site1.etempurl.com/api/authenticate/ChangeRole/',
  // GetAllHealthDirectories: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthDirectories/',
  // GetAllHealthDitricts: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthDistricts/AllHealthDistrictsByhealthDirectoryId/',
  // GetHealthDitricts: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthDistricts/',
  // GetAllHealthCareUnitById:'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/',
  // GetAllModes: 'http://almostakbalupd-001-site1.etempurl.com/api/Mode/',
  // GetAllEquimentsByEmp: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/GetAllEquimentsByEmp/',
  // AddNewCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCategories/',
  // updateCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCategories/',
  // deleteCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCategories/',
  // AddNewSubCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentSubCategories/',
  // updateSubCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentSubCategories/',
  // deleteSubCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentSubCategories/',
  // addNewOrigin: 'http://almostakbalupd-001-site1.etempurl.com/api/Origins/',
  // updateOrigin: 'http://almostakbalupd-001-site1.etempurl.com/api/Origins/',
  // deleteOrigin: 'http://almostakbalupd-001-site1.etempurl.com/api/Origins/',
  // addNewManufacturer: 'http://almostakbalupd-001-site1.etempurl.com/api/Manufacturers/',
  // updateManufacturer: 'http://almostakbalupd-001-site1.etempurl.com/api/Manufacturers/',
  // deleteManufacturer: 'http://almostakbalupd-001-site1.etempurl.com/api/Manufacturers/',
  // addNewStatus: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentStatus/',
  // updateStatus: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentStatus/',
  // deleteStatus: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentStatus/',
  // addNewPriority: 'http://almostakbalupd-001-site1.etempurl.com/api/Priorities/',
  // updatePriority: 'http://almostakbalupd-001-site1.etempurl.com/api/Priorities/',
  // deletePriority: 'http://almostakbalupd-001-site1.etempurl.com/api/Priorities/',
  // addNewDepartment: 'http://almostakbalupd-001-site1.etempurl.com/api/Departments/',
  // updateDepartment: 'http://almostakbalupd-001-site1.etempurl.com/api/Departments/',
  // deleteDepartment: 'http://almostakbalupd-001-site1.etempurl.com/api/Departments/',
  // addNewSupplier: 'http://almostakbalupd-001-site1.etempurl.com/api/Suppliers/',
  // updateSupplier: 'http://almostakbalupd-001-site1.etempurl.com/api/Suppliers/',
  // deleteSupplier: 'http://almostakbalupd-001-site1.etempurl.com/api/Suppliers/',
  // addNewMode: 'http://almostakbalupd-001-site1.etempurl.com/api/Mode/',
  // updateMode: 'http://almostakbalupd-001-site1.etempurl.com/api/Mode/',
  // deleteMode: 'http://almostakbalupd-001-site1.etempurl.com/api/Mode/',
  // GetEmployee: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/',
  // GetEquipmentEmployee: 'http://almostakbalupd-001-site1.etempurl.com/api/Employees/GetEquipmentemployees/',
  // CreateRoles: 'http://almostakbalupd-001-site1.etempurl.com/api/User/CreateRoles/',
  // AddNewMasterEquipments: 'http://almostakbalupd-001-site1.etempurl.com/api/MasterEquipment/',
  // GetAllMasterEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/MasterEquipment/',
  // UpdateMasterEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/MasterEquipment/',
  // DeleteMasterEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/MasterEquipment/',
  // GetVendors: 'http://almostakbalupd-001-site1.etempurl.com/api/Vendor',
  // AddNewWorkOrder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder',
  // AddNewMaintenance: 'http://almostakbalupd-001-site1.etempurl.com/api/Maintenance',
  // AddNewSparePart: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart',
  // GetAllRequestStatus: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/GetAllRequestStatus',
  // deleteWorkOrder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/',
  // createNewStatus: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests/createRequestStatus',
  // getAllOworkOrders: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/',
  // GetMaintenance: 'http://almostakbalupd-001-site1.etempurl.com/api/Maintenance/',
  // getOneWorkOrder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/',
  // GetSparePart: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart/',
  // UpdateWorkOrder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/',
  // UpdateMaintenance: 'http://almostakbalupd-001-site1.etempurl.com/api/Maintenance/',
  // DeleteWorkOrder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/',
  // AddWorkOrderWithoutRequest: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/AddWorkOrderWithoutRequest',
  // getOrdersWithoutRequest: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/GetAllOrdersWithoutRequest',
  // Closeorder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/CloseWorkOrder/',
  // forgetPassword: 'http://almostakbalupd-001-site1.etempurl.com/api/Authenticate/forgetPassword/',
  // resetpassword: 'http://almostakbalupd-001-site1.etempurl.com/api/Authenticate/ResetPassword/',
  // GetAllContracts: 'http://almostakbalupd-001-site1.etempurl.com/api/contract/',
  // AddContract: 'http://almostakbalupd-001-site1.etempurl.com/api/contract/',
  // DeleteContract: 'http://almostakbalupd-001-site1.etempurl.com/api/contract/',
  // UpdateContract: 'http://almostakbalupd-001-site1.etempurl.com/api/contract/',
  // GetAllEquipmentCoverages: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCoverage/',
  // AddEquipmentCoverage: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCoverage/',
  // DeleteEquipmentCoverage: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCoverage/',
  // UpdateEquipmentCoverage: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCoverage/',
  // GetAllSpareParts: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart/',
  // AddSparePart: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart/',
  // DeleteSparePart: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart/',
  // UpdateSparePart: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart/',
  // GetAllecriCodes:'http://almostakbalupd-001-site1.etempurl.com/api/ecri/',
  // updateEcriCode:'http://almostakbalupd-001-site1.etempurl.com/api/ecri/',
  // deleteEcriCode:'http://almostakbalupd-001-site1.etempurl.com/api/ecri/',
  // addEcriCode:'http://almostakbalupd-001-site1.etempurl.com/api/ecri/',
  // addNewecri:'http://almostakbalupd-001-site1.etempurl.com/api/ecri/',
  // Drug: 'http://localhost:51563/api/drugs/',


  // GetAllEquipments: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
  // GetOneEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
  // AddNewEquipments: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
  // DeleteEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
  // UpdateEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
  // GetAllHealthCareUnits: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/',
  // DeleteHealthCareUnit: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/',
  // updateHealthCareUnit: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/',
  // GetAllHealthCareUnitsByDistrictId: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/GetHealthCareUnitsByDistrictId/',
  // GetByDistrictId: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/getHealthDistrictsByempDistrictId/',
  // GetByDirectoryId:'http://almostakbalupd-001-site1.etempurl.com/api/HealthDistricts/getHealthDirectoryBydirId/',
  // addNewUnit: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/',
  // GetAllStatuses: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentStatus/',
  // GetAllPriorities: 'http://almostakbalupd-001-site1.etempurl.com/api/Priorities/',
  // GetAllManufacturers: 'http://almostakbalupd-001-site1.etempurl.com/api/Manufacturers/',
  // GetAllOrigins: 'http://almostakbalupd-001-site1.etempurl.com/api/Origins/',
  // GetAllCategories: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCategories/',
  // GetSubCategories: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentSubCategories/',
  // GetAllSubCategories: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentSubCategories/AllSubCategoriesBycategoryId/',
  // GetAllDepartments: 'http://almostakbalupd-001-site1.etempurl.com/api/Departments/',
  // GetAllSuppliers: 'http://almostakbalupd-001-site1.etempurl.com/api/Suppliers/',
  // GetAllEmployees: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/',
  // AddEmployee: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/',
  // DeleteEmployee: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/',
  // UpdateEmployee: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/',
  // GetEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
  // UploadImg: 'http://almostakbalupd-001-site1.etempurl.com/api/ImgUpload/',
  // GetAllServiceRequests: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests/',
  // GetAllRequestsByDirectory: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests/GetAllRequestsByDirectory/',
  // MakeRequest: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests',
  // UpdateRequest: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests/',
  // DeleteRequest: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests/',
  // Register: 'http://almostakbalupd-001-site1.etempurl.com/api/authenticate/register/',
  // Login: 'http://almostakbalupd-001-site1.etempurl.com/api/authenticate/Login',
  // GetUsers: 'http://almostakbalupd-001-site1.etempurl.com/api/User/',
  // getUserById: 'http://almostakbalupd-001-site1.etempurl.com/api/User/GetUserById/',
  // DeleteUser: 'http://almostakbalupd-001-site1.etempurl.com/api/User/',
  // GetUnregisteredUsers: 'http://almostakbalupd-001-site1.etempurl.com/api/User/GetUnregisteredUsers/',
  // GetAllRoles: 'http://almostakbalupd-001-site1.etempurl.com/api/User/GetAllRoles/',
  // getRoleById: 'http://almostakbalupd-001-site1.etempurl.com/api/User/GetRoleById/',
  // getEmployeeByMail: 'http://almostakbalupd-001-site1.etempurl.com/api/Employees/GetEmployeeNyMail/',
  // UpdateRole: 'http://almostakbalupd-001-site1.etempurl.com/api/authenticate/ChangeRole/',
  // GetAllHealthDirectories: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthDirectories/',
  // GetAllHealthDitricts: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthDistricts/AllHealthDistrictsByhealthDirectoryId/',
  // GetHealthDitricts: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthDistricts/',
  // GetAllHealthCareUnitById:'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/',
  // GetAllModes: 'http://almostakbalupd-001-site1.etempurl.com/api/Mode/',
  // GetAllEquimentsByEmp: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/GetAllEquimentsByEmp/',
  // AddNewCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCategories/',
  // updateCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCategories/',
  // deleteCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCategories/',
  // AddNewSubCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentSubCategories/',
  // updateSubCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentSubCategories/',
  // deleteSubCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentSubCategories/',
  // addNewOrigin: 'http://almostakbalupd-001-site1.etempurl.com/api/Origins/',
  // updateOrigin: 'http://almostakbalupd-001-site1.etempurl.com/api/Origins/',
  // deleteOrigin: 'http://almostakbalupd-001-site1.etempurl.com/api/Origins/',
  // addNewManufacturer: 'http://almostakbalupd-001-site1.etempurl.com/api/Manufacturers/',
  // updateManufacturer: 'http://almostakbalupd-001-site1.etempurl.com/api/Manufacturers/',
  // deleteManufacturer: 'http://almostakbalupd-001-site1.etempurl.com/api/Manufacturers/',
  // addNewStatus: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentStatus/',
  // updateStatus: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentStatus/',
  // deleteStatus: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentStatus/',
  // addNewPriority: 'http://almostakbalupd-001-site1.etempurl.com/api/Priorities/',
  // updatePriority: 'http://almostakbalupd-001-site1.etempurl.com/api/Priorities/',
  // deletePriority: 'http://almostakbalupd-001-site1.etempurl.com/api/Priorities/',
  // addNewDepartment: 'http://almostakbalupd-001-site1.etempurl.com/api/Departments/',
  // updateDepartment: 'http://almostakbalupd-001-site1.etempurl.com/api/Departments/',
  // deleteDepartment: 'http://almostakbalupd-001-site1.etempurl.com/api/Departments/',
  // addNewSupplier: 'http://almostakbalupd-001-site1.etempurl.com/api/Suppliers/',
  // updateSupplier: 'http://almostakbalupd-001-site1.etempurl.com/api/Suppliers/',
  // deleteSupplier: 'http://almostakbalupd-001-site1.etempurl.com/api/Suppliers/',
  // addNewMode: 'http://almostakbalupd-001-site1.etempurl.com/api/Mode/',
  // updateMode: 'http://almostakbalupd-001-site1.etempurl.com/api/Mode/',
  // deleteMode: 'http://almostakbalupd-001-site1.etempurl.com/api/Mode/',
  // GetEmployee: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/',
  // GetEquipmentEmployee: 'http://almostakbalupd-001-site1.etempurl.com/api/Employees/GetEquipmentemployees/',
  // CreateRoles: 'http://almostakbalupd-001-site1.etempurl.com/api/User/CreateRoles/',
  // AddNewMasterEquipments: 'http://almostakbalupd-001-site1.etempurl.com/api/MasterEquipment/',
  // GetAllMasterEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/MasterEquipment/',
  // UpdateMasterEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/MasterEquipment/',
  // DeleteMasterEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/MasterEquipment/',
  // GetVendors: 'http://almostakbalupd-001-site1.etempurl.com/api/Vendor',
  // AddNewWorkOrder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder',
  // AddNewMaintenance: 'http://almostakbalupd-001-site1.etempurl.com/api/Maintenance',
  // AddNewSparePart: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart',
  // GetAllRequestStatus: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/GetAllRequestStatus',
  // deleteWorkOrder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/',
  // createNewStatus: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests/createRequestStatus',
  // getAllOworkOrders: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/',
  // GetMaintenance: 'http://almostakbalupd-001-site1.etempurl.com/api/Maintenance/',
  // getOneWorkOrder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/',
  // GetSparePart: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart/',
  // UpdateWorkOrder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/',
  // UpdateMaintenance: 'http://almostakbalupd-001-site1.etempurl.com/api/Maintenance/',
  // DeleteWorkOrder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/',
  // AddWorkOrderWithoutRequest: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/AddWorkOrderWithoutRequest',
  // getOrdersWithoutRequest: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/GetAllOrdersWithoutRequest',
  // Closeorder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/CloseWorkOrder/',
  // forgetPassword: 'http://almostakbalupd-001-site1.etempurl.com/api/Authenticate/forgetPassword/',
  // resetpassword: 'http://almostakbalupd-001-site1.etempurl.com/api/Authenticate/ResetPassword/',
  // GetAllContracts: 'http://almostakbalupd-001-site1.etempurl.com/api/contract/',
  // AddContract: 'http://almostakbalupd-001-site1.etempurl.com/api/contract/',
  // DeleteContract: 'http://almostakbalupd-001-site1.etempurl.com/api/contract/',
  // UpdateContract: 'http://almostakbalupd-001-site1.etempurl.com/api/contract/',
  // GetAllEquipmentCoverages: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCoverage/',
  // AddEquipmentCoverage: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCoverage/',
  // DeleteEquipmentCoverage: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCoverage/',
  // UpdateEquipmentCoverage: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCoverage/',
  // GetAllSpareParts: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart/',
  // AddSparePart: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart/',
  // DeleteSparePart: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart/',
  // UpdateSparePart: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart/',
  // GetAllecriCodes:'http://almostakbalupd-001-site1.etempurl.com/api/ecri/',
  // updateEcriCode:'http://almostakbalupd-001-site1.etempurl.com/api/ecri/',
  // deleteEcriCode:'http://almostakbalupd-001-site1.etempurl.com/api/ecri/',
  // addEcriCode:'http://almostakbalupd-001-site1.etempurl.com/api/ecri/',
  // addNewecri:'http://almostakbalupd-001-site1.etempurl.com/api/ecri/',
  // GetAllOrganization:'http://almostakbalupd-001-site1.etempurl.com/Organization/',
  // AddOrganization:'http://almostakbalupd-001-site1.etempurl.com/Organization/',
  // DeleteOrganization:'http://almostakbalupd-001-site1.etempurl.com/Organization/',
  // UpdateOrganization:'http://almostakbalupd-001-site1.etempurl.com/Organization/', 
  
  production: false
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.





// GetAllEquipments: 'http://10.10.0.131/BioMedicalAPI/api/Equipments/',
// GetOneEquipment: 'http://10.10.0.131/BioMedicalAPI/api/Equipments/',
// AddNewEquipments: 'http://10.10.0.131/BioMedicalAPI/api/Equipments/',
// DeleteEquipment: 'http://10.10.0.131/BioMedicalAPI/api/Equipments/',
// UpdateEquipment: 'http://10.10.0.131/BioMedicalAPI/api/Equipments/',
// GetAllHealthCareUnits: 'http://10.10.0.131/BioMedicalAPI/api/HealthCareUnits/',
// DeleteHealthCareUnit: 'http://10.10.0.131/BioMedicalAPI/api/HealthCareUnits/',
// updateHealthCareUnit: 'http://10.10.0.131/BioMedicalAPI/api/HealthCareUnits/',
// GetAllHealthCareUnitsByDistrictId: 'http://10.10.0.131/BioMedicalAPI/api/HealthCareUnits/GetHealthCareUnitsByDistrictId/',
// GetByDistrictId: 'http://10.10.0.131/BioMedicalAPI/api/employees/getHealthDistrictsByempDistrictId/',
// GetByDirectoryId:'http://10.10.0.131/BioMedicalAPI/api/HealthDistricts/getHealthDirectoryBydirId/',
// addNewUnit: 'http://10.10.0.131/BioMedicalAPI/api/HealthCareUnits/',
// GetAllStatuses: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentStatus/',
// GetAllPriorities: 'http://10.10.0.131/BioMedicalAPI/api/Priorities/',
// GetAllManufacturers: 'http://10.10.0.131/BioMedicalAPI/api/Manufacturers/',
// GetAllOrigins: 'http://10.10.0.131/BioMedicalAPI/api/Origins/',
// GetAllCategories: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentCategories/',
// GetSubCategories: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentSubCategories/',
// GetAllSubCategories: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentSubCategories/AllSubCategoriesBycategoryId/',
// GetAllDepartments: 'http://10.10.0.131/BioMedicalAPI/api/Departments/',
// GetAllSuppliers: 'http://10.10.0.131/BioMedicalAPI/api/Suppliers/',
// GetAllEmployees: 'http://10.10.0.131/BioMedicalAPI/api/employees/',
// AddEmployee: 'http://10.10.0.131/BioMedicalAPI/api/employees/',
// DeleteEmployee: 'http://10.10.0.131/BioMedicalAPI/api/employees/',
// UpdateEmployee: 'http://10.10.0.131/BioMedicalAPI/api/employees/',
// GetEquipment: 'http://10.10.0.131/BioMedicalAPI/api/Equipments/',
// UploadImg: 'http://10.10.0.131/BioMedicalAPI/api/ImgUpload/',
// GetAllServiceRequests: 'http://10.10.0.131/BioMedicalAPI/api/ServiceRequests/',
// GetAllRequestsByDirectory: 'http://10.10.0.131/BioMedicalAPI/api/ServiceRequests/GetAllRequestsByDirectory/',
// MakeRequest: 'http://10.10.0.131/BioMedicalAPI/api/ServiceRequests',
// UpdateRequest: 'http://10.10.0.131/BioMedicalAPI/api/ServiceRequests/',
// DeleteRequest: 'http://10.10.0.131/BioMedicalAPI/api/ServiceRequests/',
// Register: 'http://10.10.0.131/BioMedicalAPI/api/authenticate/register/',
// Login: 'http://10.10.0.131/BioMedicalAPI/api/authenticate/Login',
// GetUsers: 'http://10.10.0.131/BioMedicalAPI/api/User/',
// getUserById: 'http://10.10.0.131/BioMedicalAPI/api/User/GetUserById/',
// DeleteUser: 'http://10.10.0.131/BioMedicalAPI/api/User/',
// GetUnregisteredUsers: 'http://10.10.0.131/BioMedicalAPI/api/User/GetUnregisteredUsers/',
// GetAllRoles: 'http://10.10.0.131/BioMedicalAPI/api/User/GetAllRoles/',
// getRoleById: 'http://10.10.0.131/BioMedicalAPI/api/User/GetRoleById/',
// getEmployeeByMail: 'http://10.10.0.131/BioMedicalAPI/api/Employees/GetEmployeeNyMail/',
// UpdateRole: 'http://10.10.0.131/BioMedicalAPI/api/authenticate/ChangeRole/',
// GetAllHealthDirectories: 'http://10.10.0.131/BioMedicalAPI/api/HealthDirectories/',
// GetAllHealthDitricts: 'http://10.10.0.131/BioMedicalAPI/api/HealthDistricts/AllHealthDistrictsByhealthDirectoryId/',
// GetHealthDitricts: 'http://10.10.0.131/BioMedicalAPI/api/HealthDistricts/',
// GetAllHealthCareUnitById:'http://10.10.0.131/BioMedicalAPI/api/HealthCareUnits/',
// GetAllModes: 'http://10.10.0.131/BioMedicalAPI/api/Mode/',
// GetAllEquimentsByEmp: 'http://10.10.0.131/BioMedicalAPI/api/Equipments/GetAllEquimentsByEmp/',
// AddNewCategory: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentCategories/',
// updateCategory: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentCategories/',
// deleteCategory: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentCategories/',
// AddNewSubCategory: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentSubCategories/',
// updateSubCategory: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentSubCategories/',
// deleteSubCategory: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentSubCategories/',
// addNewOrigin: 'http://10.10.0.131/BioMedicalAPI/api/Origins/',
// updateOrigin: 'http://10.10.0.131/BioMedicalAPI/api/Origins/',
// deleteOrigin: 'http://10.10.0.131/BioMedicalAPI/api/Origins/',
// addNewManufacturer: 'http://10.10.0.131/BioMedicalAPI/api/Manufacturers/',
// updateManufacturer: 'http://10.10.0.131/BioMedicalAPI/api/Manufacturers/',
// deleteManufacturer: 'http://10.10.0.131/BioMedicalAPI/api/Manufacturers/',
// addNewStatus: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentStatus/',
// updateStatus: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentStatus/',
// deleteStatus: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentStatus/',
// addNewPriority: 'http://10.10.0.131/BioMedicalAPI/api/Priorities/',
// updatePriority: 'http://10.10.0.131/BioMedicalAPI/api/Priorities/',
// deletePriority: 'http://10.10.0.131/BioMedicalAPI/api/Priorities/',
// addNewDepartment: 'http://10.10.0.131/BioMedicalAPI/api/Departments/',
// updateDepartment: 'http://10.10.0.131/BioMedicalAPI/api/Departments/',
// deleteDepartment: 'http://10.10.0.131/BioMedicalAPI/api/Departments/',
// addNewSupplier: 'http://10.10.0.131/BioMedicalAPI/api/Suppliers/',
// updateSupplier: 'http://10.10.0.131/BioMedicalAPI/api/Suppliers/',
// deleteSupplier: 'http://10.10.0.131/BioMedicalAPI/api/Suppliers/',
// addNewMode: 'http://10.10.0.131/BioMedicalAPI/api/Mode/',
// updateMode: 'http://10.10.0.131/BioMedicalAPI/api/Mode/',
// deleteMode: 'http://10.10.0.131/BioMedicalAPI/api/Mode/',
// GetEmployee: 'http://10.10.0.131/BioMedicalAPI/api/employees/',
// GetEquipmentEmployee: 'http://10.10.0.131/BioMedicalAPI/api/Employees/GetEquipmentemployees/',
// CreateRoles: 'http://10.10.0.131/BioMedicalAPI/api/User/CreateRoles/',
// AddNewMasterEquipments: 'http://10.10.0.131/BioMedicalAPI/api/MasterEquipment/',
// GetAllMasterEquipment: 'http://10.10.0.131/BioMedicalAPI/api/MasterEquipment/',
// UpdateMasterEquipment: 'http://10.10.0.131/BioMedicalAPI/api/MasterEquipment/',
// DeleteMasterEquipment: 'http://10.10.0.131/BioMedicalAPI/api/MasterEquipment/',
// GetVendors: 'http://10.10.0.131/BioMedicalAPI/api/Vendor',
// AddNewWorkOrder: 'http://10.10.0.131/BioMedicalAPI/api/WorkOrder',
// AddNewMaintenance: 'http://10.10.0.131/BioMedicalAPI/api/Maintenance',
// AddNewSparePart: 'http://10.10.0.131/BioMedicalAPI/api/SparePart',
// GetAllRequestStatus: 'http://10.10.0.131/BioMedicalAPI/api/WorkOrder/GetAllRequestStatus',
// deleteWorkOrder: 'http://10.10.0.131/BioMedicalAPI/api/WorkOrder/',
// createNewStatus: 'http://10.10.0.131/BioMedicalAPI/api/ServiceRequests/createRequestStatus',
// getAllOworkOrders: 'http://10.10.0.131/BioMedicalAPI/api/WorkOrder/',
// GetMaintenance: 'http://10.10.0.131/BioMedicalAPI/api/Maintenance/',
// getOneWorkOrder: 'http://10.10.0.131/BioMedicalAPI/api/WorkOrder/',
// GetSparePart: 'http://10.10.0.131/BioMedicalAPI/api/SparePart/',
// UpdateWorkOrder: 'http://10.10.0.131/BioMedicalAPI/api/WorkOrder/',
// UpdateMaintenance: 'http://10.10.0.131/BioMedicalAPI/api/Maintenance/',
// DeleteWorkOrder: 'http://10.10.0.131/BioMedicalAPI/api/WorkOrder/',
// AddWorkOrderWithoutRequest: 'http://10.10.0.131/BioMedicalAPI/api/WorkOrder/AddWorkOrderWithoutRequest',
// getOrdersWithoutRequest: 'http://10.10.0.131/BioMedicalAPI/api/WorkOrder/GetAllOrdersWithoutRequest',
// Closeorder: 'http://10.10.0.131/BioMedicalAPI/api/WorkOrder/CloseWorkOrder/',
// forgetPassword: 'http://10.10.0.131/BioMedicalAPI/api/Authenticate/forgetPassword/',
// resetpassword: 'http://10.10.0.131/BioMedicalAPI/api/Authenticate/ResetPassword/',
// GetAllContracts: 'http://10.10.0.131/BioMedicalAPI/api/contract/',
// AddContract: 'http://10.10.0.131/BioMedicalAPI/api/contract/',
// DeleteContract: 'http://10.10.0.131/BioMedicalAPI/api/contract/',
// UpdateContract: 'http://10.10.0.131/BioMedicalAPI/api/contract/',
// GetAllEquipmentCoverages: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentCoverage/',
// AddEquipmentCoverage: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentCoverage/',
// DeleteEquipmentCoverage: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentCoverage/',
// UpdateEquipmentCoverage: 'http://10.10.0.131/BioMedicalAPI/api/EquipmentCoverage/',
// GetAllSpareParts: 'http://10.10.0.131/BioMedicalAPI/api/SparePart/',
// AddSparePart: 'http://10.10.0.131/BioMedicalAPI/api/SparePart/',
// DeleteSparePart: 'http://10.10.0.131/BioMedicalAPI/api/SparePart/',
// UpdateSparePart: 'http://10.10.0.131/BioMedicalAPI/api/SparePart/',
// GetAllecriCodes:'http://10.10.0.131/BioMedicalAPI/api/ecri/',
// updateEcriCode:'http://10.10.0.131/BioMedicalAPI/api/ecri/',
// deleteEcriCode:'http://10.10.0.131/BioMedicalAPI/api/ecri/',
// addEcriCode:'http://10.10.0.131/BioMedicalAPI/api/ecri/',
// addNewecri:'http://10.10.0.131/BioMedicalAPI/api/ecri/',
// GetAllOrganization:'http://10.10.0.131/BioMedicalAPI/Organization/',
// AddOrganization:'http://10.10.0.131/BioMedicalAPI/Organization/',
// DeleteOrganization:'http://10.10.0.131/BioMedicalAPI/Organization/',
// UpdateOrganization:'http://10.10.0.131/BioMedicalAPI/Organization/', 
// GetOrganization:'http://10.10.0.131/BioMedicalAPI/Organization/',


////////////////////////////////////////////////////////////////////////////////////////////

// GetAllEquipments: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
//   GetOneEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
//   AddNewEquipments: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
//   DeleteEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
//   UpdateEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
//   GetAllHealthCareUnits: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/',
//   DeleteHealthCareUnit: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/',
//   updateHealthCareUnit: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/',
//   GetAllHealthCareUnitsByDistrictId: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/GetHealthCareUnitsByDistrictId/',
//   // GetByDistrictId: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/getHealthDistrictsByempDistrictId/',
//   GetByDirectoryId:'http://almostakbalupd-001-site1.etempurl.com/api/HealthDistricts/getHealthDirectoryBydirId/',
//   addNewUnit: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/',
//   GetAllStatuses: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentStatus/',
//   GetAllPriorities: 'http://almostakbalupd-001-site1.etempurl.com/api/Priorities/',
//   GetAllManufacturers: 'http://almostakbalupd-001-site1.etempurl.com/api/Manufacturers/',
//   GetAllOrigins: 'http://almostakbalupd-001-site1.etempurl.com/api/Origins/',
//   GetAllCategories: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCategories/',
//   GetSubCategories: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentSubCategories/',
//   GetAllSubCategories: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentSubCategories/AllSubCategoriesBycategoryId/',
//   GetAllDepartments: 'http://almostakbalupd-001-site1.etempurl.com/api/Departments/',
//   GetAllSuppliers: 'http://almostakbalupd-001-site1.etempurl.com/api/Suppliers/',
//   // GetAllEmployees: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/',
//   // AddEmployee: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/',
//   // DeleteEmployee: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/',
//   // UpdateEmployee: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/',
//   GetEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/',
//   UploadImg: 'http://almostakbalupd-001-site1.etempurl.com/api/ImgUpload/',
//   GetAllServiceRequests: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests/',
//   GetAllRequestsByDirectory: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests/GetAllRequestsByDirectory/',
//   MakeRequest: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests',
//   UpdateRequest: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests/',
//   DeleteRequest: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests/',
//   Register: 'http://almostakbalupd-001-site1.etempurl.com/api/authenticate/register/',
//   Login: 'http://almostakbalupd-001-site1.etempurl.com/api/authenticate/Login',
//   GetUsers: 'http://almostakbalupd-001-site1.etempurl.com/api/User/',
//   getUserById: 'http://almostakbalupd-001-site1.etempurl.com/api/User/GetUserById/',
//   DeleteUser: 'http://almostakbalupd-001-site1.etempurl.com/api/User/',
//   GetUnregisteredUsers: 'http://almostakbalupd-001-site1.etempurl.com/api/User/GetUnregisteredUsers/',
//   GetAllRoles: 'http://almostakbalupd-001-site1.etempurl.com/api/User/GetAllRoles/',
//   getRoleById: 'http://almostakbalupd-001-site1.etempurl.com/api/User/GetRoleById/',
//   // getEmployeeByMail: 'http://almostakbalupd-001-site1.etempurl.com/api/Employees/GetEmployeeNyMail/',
//   UpdateRole: 'http://almostakbalupd-001-site1.etempurl.com/api/authenticate/ChangeRole/',
//   GetAllHealthDirectories: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthDirectories/',
//   GetAllHealthDitricts: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthDistricts/AllHealthDistrictsByhealthDirectoryId/',
//   GetHealthDitricts: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthDistricts/',
//   GetAllHealthCareUnitById:'http://almostakbalupd-001-site1.etempurl.com/api/HealthCareUnits/',
//   GetAllModes: 'http://almostakbalupd-001-site1.etempurl.com/api/Mode/',
//   // GetAllEquimentsByEmp: 'http://almostakbalupd-001-site1.etempurl.com/api/Equipments/GetAllEquimentsByEmp/',
//   AddNewCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCategories/',
//   updateCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCategories/',
//   deleteCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCategories/',
//   AddNewSubCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentSubCategories/',
//   updateSubCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentSubCategories/',
//   deleteSubCategory: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentSubCategories/',
//   addNewOrigin: 'http://almostakbalupd-001-site1.etempurl.com/api/Origins/',
//   updateOrigin: 'http://almostakbalupd-001-site1.etempurl.com/api/Origins/',
//   deleteOrigin: 'http://almostakbalupd-001-site1.etempurl.com/api/Origins/',
//   addNewManufacturer: 'http://almostakbalupd-001-site1.etempurl.com/api/Manufacturers/',
//   updateManufacturer: 'http://almostakbalupd-001-site1.etempurl.com/api/Manufacturers/',
//   deleteManufacturer: 'http://almostakbalupd-001-site1.etempurl.com/api/Manufacturers/',
//   addNewStatus: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentStatus/',
//   updateStatus: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentStatus/',
//   deleteStatus: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentStatus/',
//   addNewPriority: 'http://almostakbalupd-001-site1.etempurl.com/api/Priorities/',
//   updatePriority: 'http://almostakbalupd-001-site1.etempurl.com/api/Priorities/',
//   deletePriority: 'http://almostakbalupd-001-site1.etempurl.com/api/Priorities/',
//   addNewDepartment: 'http://almostakbalupd-001-site1.etempurl.com/api/Departments/',
//   updateDepartment: 'http://almostakbalupd-001-site1.etempurl.com/api/Departments/',
//   deleteDepartment: 'http://almostakbalupd-001-site1.etempurl.com/api/Departments/',
//   addNewSupplier: 'http://almostakbalupd-001-site1.etempurl.com/api/Suppliers/',
//   updateSupplier: 'http://almostakbalupd-001-site1.etempurl.com/api/Suppliers/',
//   deleteSupplier: 'http://almostakbalupd-001-site1.etempurl.com/api/Suppliers/',
//   addNewMode: 'http://almostakbalupd-001-site1.etempurl.com/api/Mode/',
//   updateMode: 'http://almostakbalupd-001-site1.etempurl.com/api/Mode/',
//   deleteMode: 'http://almostakbalupd-001-site1.etempurl.com/api/Mode/',
//   // GetEmployee: 'http://almostakbalupd-001-site1.etempurl.com/api/employees/',
//   // GetEquipmentEmployee: 'http://almostakbalupd-001-site1.etempurl.com/api/Employees/GetEquipmentemployees/',
//   CreateRoles: 'http://almostakbalupd-001-site1.etempurl.com/api/User/CreateRoles/',
//   AddNewMasterEquipments: 'http://almostakbalupd-001-site1.etempurl.com/api/MasterEquipment/',
//   GetAllMasterEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/MasterEquipment/',
//   UpdateMasterEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/MasterEquipment/',
//   DeleteMasterEquipment: 'http://almostakbalupd-001-site1.etempurl.com/api/MasterEquipment/',
//   GetVendors: 'http://almostakbalupd-001-site1.etempurl.com/api/Vendor',
//   AddNewWorkOrder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder',
//   AddNewMaintenance: 'http://almostakbalupd-001-site1.etempurl.com/api/Maintenance',
//   AddNewSparePart: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart',
//   GetAllRequestStatus: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/GetAllRequestStatus',
//   deleteWorkOrder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/',
//   createNewStatus: 'http://almostakbalupd-001-site1.etempurl.com/api/ServiceRequests/createRequestStatus',
//   getAllOworkOrders: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/',
//   GetMaintenance: 'http://almostakbalupd-001-site1.etempurl.com/api/Maintenance/',
//   getOneWorkOrder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/',
//   GetSparePart: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart/',
//   UpdateWorkOrder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/',
//   UpdateMaintenance: 'http://almostakbalupd-001-site1.etempurl.com/api/Maintenance/',
//   DeleteWorkOrder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/',
//   AddWorkOrderWithoutRequest: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/AddWorkOrderWithoutRequest',
//   getOrdersWithoutRequest: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/GetAllOrdersWithoutRequest',
//   Closeorder: 'http://almostakbalupd-001-site1.etempurl.com/api/WorkOrder/CloseWorkOrder/',
//   forgetPassword: 'http://almostakbalupd-001-site1.etempurl.com/api/Authenticate/forgetPassword/',
//   resetpassword: 'http://almostakbalupd-001-site1.etempurl.com/api/Authenticate/ResetPassword/',
//   GetAllContracts: 'http://almostakbalupd-001-site1.etempurl.com/api/contract/',
//   AddContract: 'http://almostakbalupd-001-site1.etempurl.com/api/contract/',
//   DeleteContract: 'http://almostakbalupd-001-site1.etempurl.com/api/contract/',
//   UpdateContract: 'http://almostakbalupd-001-site1.etempurl.com/api/contract/',
//   GetAllEquipmentCoverages: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCoverage/',
//   AddEquipmentCoverage: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCoverage/',
//   DeleteEquipmentCoverage: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCoverage/',
//   UpdateEquipmentCoverage: 'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentCoverage/',
//   GetAllSpareParts: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart/',
//   AddSparePart: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart/',
//   DeleteSparePart: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart/',
//   UpdateSparePart: 'http://almostakbalupd-001-site1.etempurl.com/api/SparePart/',
//   GetAllecriCodes:'http://almostakbalupd-001-site1.etempurl.com/api/ecri/',
//   updateEcriCode:'http://almostakbalupd-001-site1.etempurl.com/api/ecri/',
//   deleteEcriCode:'http://almostakbalupd-001-site1.etempurl.com/api/ecri/',
//   addEcriCode:'http://almostakbalupd-001-site1.etempurl.com/api/ecri/',
//   addNewecri:'http://almostakbalupd-001-site1.etempurl.com/api/ecri/',
//   GetAllOrganization:'http://almostakbalupd-001-site1.etempurl.com/api/Organization/',
//   AddOrganization:'http://almostakbalupd-001-site1.etempurl.com/api/Organization/',
//   DeleteOrganization:'http://almostakbalupd-001-site1.etempurl.com/api/Organization/',
//   UpdateOrganization:'http://almostakbalupd-001-site1.etempurl.com/api/Organization/', 
//   GetOrganization:'http://almostakbalupd-001-site1.etempurl.com/api/Organization/',
//   GetHealthDirectoryIdByName:'http://almostakbalupd-001-site1.etempurl.com/api/HealthDirectories/GetHealthDirectoryIdByName/',
//   GetEquipmentAttachmentIDs:'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentAttachments/upload/',
//   GetEquipmentAttachments:'http://almostakbalupd-001-site1.etempurl.com/api/EquipmentAttachments/getEquipAttachmentsWithNoEquipment',
//   GetAllUsersByHealthcareunitId:'http://almostakbalupd-001-site1.etempurl.com/api/AllUsersByHealthcareunitId/',
//   GetAllUsersByhealthDirectoryId:'http://almostakbalupd-001-site1.etempurl.com/api/AllUsersByhealthDirectoryId/',
//   GetAllUsersByhealthDistrictId:'http://almostakbalupd-001-site1.etempurl.com/api/AllUsersByhealthDistrictId/',
//   GetAllUsersByOrganizationId:'http://almostakbalupd-001-site1.etempurl.com/api/AllUsersByOrganizationId/',
//   GetAllHealthDitrictsByDirectoryName: 'http://almostakbalupd-001-site1.etempurl.com/api/HealthDistricts/AllHealthDistrictsByhealthDirectoryName/',
