export class HealthCareUnit{
    id:number;
    name:string;
    nameAr:string;
    address:string;
    director:string;
    phone:string;
    mobile:string;
    email:string;
    long:number;
    lat:number;
    code:string;
    cityId:number;
    governorateId:number;
    suborganizationId:number;
    cityName:string;
    cityNameAr:string;
    governorateName:string;
    governorateNameAr:string;
    subOrganizationName:string;
    subOrganizationNameAr:string;
}